#!/usr/bin/env bash
# performing a 301 moved permanently
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

rep_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/mgemoraw permanent;"
sudo sed -i "s/server_name _;/$rep_str/" /etc/nginx/sites-enabled/default

sudo service nginx restart