#!/usr/bin/env bash
# sets up a new 404 request page

sudo apt-get update
sudo apt-get install -y nignx

# creawting index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

err_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$err_str/" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# creating a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# restarting service after changes
sudo seveice nginx restart
