#!/usr/bin/env bash
# configure nginx to custom header
sudo apt-get -y update
sudo apt-get -y install nginx

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https:/github.com/mgemoraw;
    }
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-enabled/default
# start nginx
sudo service nginx start