#!/usr/bin/env bash
# Configure HAproxy in load balancer
sudo apt-get update -y
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install -y haproxy=2.0\*
echo -e "
    frontend http
    bind *:80
    mode http
    default_backend web-backend

    backend web-backend
    balance roundrobin
    server 203064-web-01 100.25.16.47:80 check
    server 203064-web-02 100.25.179.233:80 check
    " >> /etc/haproxy/haproxy.cfg
    
service haproxy start
