#!/usr/bin/env bash
# Displays the contents of a file "/etc/passwd"
# Only displays username, user id, and path of user home directory

while read -r passwd
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "etc/passwd"

