#!/usr/bin/env bash
# Parses Apache log files in list fomrat
# Groups visitors by IP and HTTP status code
# Displays the number of occureances, IP, and HTTP status
# code of log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
