#!/usr/bin/env bash
# prints "Best School" 10 times using while loop

counter=1

while ((counter<=10))
do
    echo "Best School"
    if [ $counter == 9 ]
    then
    	echo "Hi"
    fi
    ((counter++))
    
done