#!/usr/bin/env bash
# prints "Best School" 10 times using while loop
# prints bad luck for 4, good luck for 8

counter=1

while ((counter<=10))
do
    if [ $counter == 4 ]
    then
    	echo "bad luck"
    elif [ $counter == 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
    
done
