#!/usr/bin/env bash
# prints "Best School" 10 times using while loop

counter=1

while ((counter<=20))
do
    echo $counter
    if [ $counter == 4 ]
    then
    	echo "bad luck from China"
    elif [ $counter == 9 ]
    then
        echo "bad luck from Japan"
    elif [ $counter == 17 ]
        then
        echo "bad luck from Italy"
    fi
    ((counter++))
    
done