#!/usr/bin/env bash
# Displays all acive IPv4 addresses

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
#!/usr/bin/env bash
# Listens on port 98 on localhost

nc -l localhost 98
